# Generated by Django 5.1.2 on 2024-12-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mister_ed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='lat',
            field=models.FloatField(blank=True, default=48.401936761021915),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lng',
            field=models.FloatField(blank=True, default=-123.34136076541516),
        ),
    ]
