# Generated by Django 5.1.2 on 2024-11-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mister_ed', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_photos/default.webp', upload_to='profile_photos/'),
        ),
    ]
